/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Business.RentCarSystem;
import Entities.Abstract.User;
import Entities.Concrete.Car;
import Entities.Concrete.Customer;
import Entities.Concrete.Gallery;
import Entities.Concrete.GalleryOwner;
import Entities.Concrete.Order;
import Helper.HelperMethods;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author Lian La-Fey
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    
    private int currentUserIndex = 0;
    private ArrayList<User> users = new ArrayList<>( RentCarSystem.getUserList() );
    
    public Admin() {
        initComponents();
        initializeAppInfo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlParent = new javax.swing.JPanel();
        pnlLeft = new javax.swing.JPanel();
        pnlExit = new javax.swing.JPanel();
        lblExitIcon = new javax.swing.JLabel();
        lblExitText = new javax.swing.JLabel();
        lblExitColor = new javax.swing.JLabel();
        lblAppInf = new javax.swing.JLabel();
        lblTotalCust = new javax.swing.JLabel();
        lblTotalCustVal = new javax.swing.JLabel();
        lblTotalGalOwnVal = new javax.swing.JLabel();
        lblTotalGalOwn = new javax.swing.JLabel();
        lblTotalGalleries = new javax.swing.JLabel();
        lblTotalGalleriesVal = new javax.swing.JLabel();
        lblTotalCars = new javax.swing.JLabel();
        lblTotalCarsVal = new javax.swing.JLabel();
        lblTotalOrders = new javax.swing.JLabel();
        lblTotalOrdersVal = new javax.swing.JLabel();
        lblLeftPnlBackground = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblSimpleHomeIcon = new javax.swing.JLabel();
        lblAdminIcon = new javax.swing.JLabel();
        lblAdminIconBackground = new javax.swing.JLabel();
        lblAdminBackground2 = new javax.swing.JLabel();
        layerPnl = new javax.swing.JLayeredPane();
        pnlHome = new javax.swing.JPanel();
        pnlViewUsers = new javax.swing.JPanel();
        lblViewUsers = new javax.swing.JLabel();
        lblViewUsersIcon = new javax.swing.JLabel();
        lblBackgroundViewUsers = new javax.swing.JLabel();
        pnlViewOrders = new javax.swing.JPanel();
        lblViewOrders = new javax.swing.JLabel();
        lblViewOrdersIcon = new javax.swing.JLabel();
        lblBackgroundViewOrders = new javax.swing.JLabel();
        pnlAddGalleryOwner = new javax.swing.JPanel();
        lblAddGalleryOwner = new javax.swing.JLabel();
        lblAddGalleryOwnerIcon = new javax.swing.JLabel();
        lblBackgroundAddGalOwn = new javax.swing.JLabel();
        pnlViewCars = new javax.swing.JPanel();
        lblViewCars = new javax.swing.JLabel();
        lblViewCarsIcon = new javax.swing.JLabel();
        lblBackgroundViewCars = new javax.swing.JLabel();
        pnlShowUsers = new javax.swing.JPanel();
        lblProfilePic = new javax.swing.JLabel();
        lblUserFullName = new javax.swing.JLabel();
        lblUserFullNameVal = new javax.swing.JLabel();
        lblUserGender = new javax.swing.JLabel();
        lblUserGenderVal = new javax.swing.JLabel();
        lblUserAge = new javax.swing.JLabel();
        lblUserAgeVal = new javax.swing.JLabel();
        lblPhoneNum = new javax.swing.JLabel();
        lblPhoneNumVal = new javax.swing.JLabel();
        lblMailVal = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        lblUserNameVal = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblUserName1 = new javax.swing.JLabel();
        lblUserNameVal1 = new javax.swing.JLabel();
        lblTotalOrder = new javax.swing.JLabel();
        lblTotalOrderVal = new javax.swing.JLabel();
        lblUserBg1 = new javax.swing.JLabel();
        lblUserBg2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlParent.setBackground(new java.awt.Color(255, 255, 255));
        pnlParent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnlLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlExit.setBackground(new java.awt.Color(255, 255, 255));
        pnlExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlExit.setOpaque(false);
        pnlExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblExitIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit48.png"))); // NOI18N
        pnlExit.add(lblExitIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 60));

        lblExitText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblExitText.setForeground(new java.awt.Color(30, 107, 255));
        lblExitText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExitText.setText("Sign Out");
        pnlExit.add(lblExitText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 90, 60));

        lblExitColor.setBackground(new java.awt.Color(255, 204, 255));
        lblExitColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitColorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitColorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitColorMouseExited(evt);
            }
        });
        pnlExit.add(lblExitColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 60));

        pnlLeft.add(pnlExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 310, -1));

        lblAppInf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAppInf.setForeground(new java.awt.Color(30, 107, 255));
        lblAppInf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppInf.setText("Application Information");
        pnlLeft.add(lblAppInf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 40));

        lblTotalCust.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalCust.setForeground(new java.awt.Color(30, 107, 255));
        lblTotalCust.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalCust.setText("Total Customers: ");
        pnlLeft.add(lblTotalCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 150, 30));

        lblTotalCustVal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalCustVal.setForeground(new java.awt.Color(30, 107, 255));
        lblTotalCustVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalCustVal.setText("val");
        pnlLeft.add(lblTotalCustVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 150, 30));

        lblTotalGalOwnVal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalGalOwnVal.setForeground(new java.awt.Color(30, 107, 255));
        lblTotalGalOwnVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalGalOwnVal.setText("val");
        pnlLeft.add(lblTotalGalOwnVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 150, 30));

        lblTotalGalOwn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalGalOwn.setForeground(new java.awt.Color(30, 107, 255));
        lblTotalGalOwn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalGalOwn.setText("Total Gal. Owners:");
        pnlLeft.add(lblTotalGalOwn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 150, 30));

        lblTotalGalleries.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalGalleries.setForeground(new java.awt.Color(30, 107, 255));
        lblTotalGalleries.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalGalleries.setText("Total Galleries:");
        pnlLeft.add(lblTotalGalleries, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 150, 30));

        lblTotalGalleriesVal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalGalleriesVal.setForeground(new java.awt.Color(30, 107, 255));
        lblTotalGalleriesVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalGalleriesVal.setText("val");
        pnlLeft.add(lblTotalGalleriesVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 150, 30));

        lblTotalCars.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalCars.setForeground(new java.awt.Color(30, 107, 255));
        lblTotalCars.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalCars.setText("Total Cars:");
        pnlLeft.add(lblTotalCars, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, 30));

        lblTotalCarsVal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalCarsVal.setForeground(new java.awt.Color(30, 107, 255));
        lblTotalCarsVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalCarsVal.setText("val");
        pnlLeft.add(lblTotalCarsVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 150, 30));

        lblTotalOrders.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalOrders.setForeground(new java.awt.Color(30, 107, 255));
        lblTotalOrders.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalOrders.setText("Total Orders");
        pnlLeft.add(lblTotalOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 150, 30));

        lblTotalOrdersVal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalOrdersVal.setForeground(new java.awt.Color(30, 107, 255));
        lblTotalOrdersVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalOrdersVal.setText("val");
        pnlLeft.add(lblTotalOrdersVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 150, 30));

        lblLeftPnlBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/leftPnlBackground.png"))); // NOI18N
        pnlLeft.add(lblLeftPnlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 330));

        pnlParent.add(pnlLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 310, 330));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(30, 107, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("ADMINISTRATOR CONTROL SYSTEM");
        pnlParent.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 730, 60));

        lblSimpleHomeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSimpleHomeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeIconAdmin.png"))); // NOI18N
        lblSimpleHomeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSimpleHomeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSimpleHomeIconMouseClicked(evt);
            }
        });
        pnlParent.add(lblSimpleHomeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 60, 60));

        lblAdminIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdminIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/administrator.png"))); // NOI18N
        pnlParent.add(lblAdminIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 96, 96));

        lblAdminIconBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdminIconBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundColor96.png"))); // NOI18N
        pnlParent.add(lblAdminIconBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 96, 96));

        lblAdminBackground2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdminBackground2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundColor930.png"))); // NOI18N
        lblAdminBackground2.setToolTipText("");
        pnlParent.add(lblAdminBackground2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 930, 60));

        layerPnl.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(255, 255, 255));

        pnlViewUsers.setBackground(new java.awt.Color(255, 255, 255));
        pnlViewUsers.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 235, 250), 3, true));
        pnlViewUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlViewUsers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblViewUsers.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblViewUsers.setForeground(new java.awt.Color(30, 107, 255));
        lblViewUsers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewUsers.setText("View Users");
        pnlViewUsers.add(lblViewUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 115, 220, 50));

        lblViewUsersIcon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblViewUsersIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewUsersIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/people100.png"))); // NOI18N
        pnlViewUsers.add(lblViewUsersIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 14, 220, 115));

        lblBackgroundViewUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white220_165.png"))); // NOI18N
        lblBackgroundViewUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackgroundViewUsersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBackgroundViewUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBackgroundViewUsersMouseExited(evt);
            }
        });
        pnlViewUsers.add(lblBackgroundViewUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 210, 155));

        pnlViewOrders.setBackground(new java.awt.Color(255, 255, 255));
        pnlViewOrders.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 235, 250), 3, true));
        pnlViewOrders.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlViewOrders.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblViewOrders.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblViewOrders.setForeground(new java.awt.Color(30, 107, 255));
        lblViewOrders.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewOrders.setText("View Orders");
        pnlViewOrders.add(lblViewOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 115, 220, 50));

        lblViewOrdersIcon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblViewOrdersIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewOrdersIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ordersIcon100.png"))); // NOI18N
        pnlViewOrders.add(lblViewOrdersIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 14, 220, 115));

        lblBackgroundViewOrders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white220_165.png"))); // NOI18N
        lblBackgroundViewOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBackgroundViewOrdersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBackgroundViewOrdersMouseExited(evt);
            }
        });
        pnlViewOrders.add(lblBackgroundViewOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 210, 155));

        pnlAddGalleryOwner.setBackground(new java.awt.Color(255, 255, 255));
        pnlAddGalleryOwner.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 235, 250), 3, true));
        pnlAddGalleryOwner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlAddGalleryOwner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddGalleryOwner.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAddGalleryOwner.setForeground(new java.awt.Color(30, 107, 255));
        lblAddGalleryOwner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddGalleryOwner.setText("Add Gallery Owner");
        pnlAddGalleryOwner.add(lblAddGalleryOwner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 105, 220, 60));

        lblAddGalleryOwnerIcon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAddGalleryOwnerIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddGalleryOwnerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addGalleryOwnerIcon100.png"))); // NOI18N
        pnlAddGalleryOwner.add(lblAddGalleryOwnerIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 220, -1));

        lblBackgroundAddGalOwn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white220_165.png"))); // NOI18N
        lblBackgroundAddGalOwn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBackgroundAddGalOwnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBackgroundAddGalOwnMouseExited(evt);
            }
        });
        pnlAddGalleryOwner.add(lblBackgroundAddGalOwn, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 210, 155));

        pnlViewCars.setBackground(new java.awt.Color(255, 255, 255));
        pnlViewCars.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 235, 250), 3, true));
        pnlViewCars.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlViewCars.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblViewCars.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblViewCars.setForeground(new java.awt.Color(30, 107, 255));
        lblViewCars.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewCars.setText("View Cars");
        pnlViewCars.add(lblViewCars, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 115, 220, 50));

        lblViewCarsIcon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblViewCarsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewCarsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carsIcon100.png"))); // NOI18N
        pnlViewCars.add(lblViewCarsIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 14, 220, 115));

        lblBackgroundViewCars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white220_165.png"))); // NOI18N
        lblBackgroundViewCars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBackgroundViewCarsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBackgroundViewCarsMouseExited(evt);
            }
        });
        pnlViewCars.add(lblBackgroundViewCars, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 210, 155));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAddGalleryOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlViewUsers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlViewCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlViewOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlViewOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlViewUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlViewCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAddGalleryOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layerPnl.add(pnlHome, "card2");

        pnlShowUsers.setBackground(new java.awt.Color(255, 255, 255));
        pnlShowUsers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProfilePic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfilePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/guest.png"))); // NOI18N
        pnlShowUsers.add(lblProfilePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 150, 150));

        lblUserFullName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUserFullName.setForeground(new java.awt.Color(30, 107, 255));
        lblUserFullName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUserFullName.setText("Full Name:");
        pnlShowUsers.add(lblUserFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 100, 30));

        lblUserFullNameVal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUserFullNameVal.setForeground(new java.awt.Color(30, 107, 255));
        lblUserFullNameVal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserFullNameVal.setText("val");
        lblUserFullNameVal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 1));
        pnlShowUsers.add(lblUserFullNameVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 160, 30));

        lblUserGender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUserGender.setForeground(new java.awt.Color(30, 107, 255));
        lblUserGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUserGender.setText("Gender:");
        pnlShowUsers.add(lblUserGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 100, 30));

        lblUserGenderVal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUserGenderVal.setForeground(new java.awt.Color(30, 107, 255));
        lblUserGenderVal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserGenderVal.setText("val");
        lblUserGenderVal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 1));
        pnlShowUsers.add(lblUserGenderVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 160, 30));

        lblUserAge.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUserAge.setForeground(new java.awt.Color(30, 107, 255));
        lblUserAge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUserAge.setText("Age:");
        pnlShowUsers.add(lblUserAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 100, 30));

        lblUserAgeVal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUserAgeVal.setForeground(new java.awt.Color(30, 107, 255));
        lblUserAgeVal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserAgeVal.setText("val");
        lblUserAgeVal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 1));
        pnlShowUsers.add(lblUserAgeVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 160, 30));

        lblPhoneNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPhoneNum.setForeground(new java.awt.Color(30, 107, 255));
        lblPhoneNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPhoneNum.setText("Phone Number:");
        pnlShowUsers.add(lblPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 100, 30));

        lblPhoneNumVal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPhoneNumVal.setForeground(new java.awt.Color(30, 107, 255));
        lblPhoneNumVal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPhoneNumVal.setText("val");
        lblPhoneNumVal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 1));
        pnlShowUsers.add(lblPhoneNumVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 160, 30));

        lblMailVal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMailVal.setForeground(new java.awt.Color(30, 107, 255));
        lblMailVal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMailVal.setText("val");
        lblMailVal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 1));
        pnlShowUsers.add(lblMailVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 160, 30));

        lblMail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMail.setForeground(new java.awt.Color(30, 107, 255));
        lblMail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMail.setText("Mail Address:");
        pnlShowUsers.add(lblMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 130, 30));

        lblUserNameVal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUserNameVal.setForeground(new java.awt.Color(30, 107, 255));
        lblUserNameVal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserNameVal.setText("val");
        lblUserNameVal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 1));
        pnlShowUsers.add(lblUserNameVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 160, 30));

        lblUserName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(30, 107, 255));
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUserName.setText("User Name:");
        pnlShowUsers.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 130, 30));

        lblUserName1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUserName1.setForeground(new java.awt.Color(30, 107, 255));
        lblUserName1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUserName1.setText("Home Address:");
        pnlShowUsers.add(lblUserName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 130, 30));

        lblUserNameVal1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUserNameVal1.setForeground(new java.awt.Color(30, 107, 255));
        lblUserNameVal1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserNameVal1.setText("val");
        lblUserNameVal1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 1));
        pnlShowUsers.add(lblUserNameVal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 160, 30));

        lblTotalOrder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalOrder.setForeground(new java.awt.Color(30, 107, 255));
        lblTotalOrder.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalOrder.setText("Total Order:");
        pnlShowUsers.add(lblTotalOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 130, 30));

        lblTotalOrderVal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTotalOrderVal.setForeground(new java.awt.Color(30, 107, 255));
        lblTotalOrderVal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalOrderVal.setText("val");
        lblTotalOrderVal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 1));
        pnlShowUsers.add(lblTotalOrderVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 160, 30));

        lblUserBg1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUserBg1.setForeground(new java.awt.Color(30, 107, 255));
        lblUserBg1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUserBg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundColor930.png"))); // NOI18N
        pnlShowUsers.add(lblUserBg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 610, 30));

        lblUserBg2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUserBg2.setForeground(new java.awt.Color(30, 107, 255));
        lblUserBg2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUserBg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundColor930.png"))); // NOI18N
        pnlShowUsers.add(lblUserBg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 610, 30));

        layerPnl.add(pnlShowUsers, "card3");

        pnlParent.add(layerPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 104, 610, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlParent, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void initializeAppInfo() {
        //lblTotalCustVal.setText( Customer.getTotal_customer() + GalleryOwner. );
        lblTotalCustVal.setText( Customer.getTotal_customer() + "" );
        lblTotalGalOwnVal.setText( (RentCarSystem.getUserList().size() -  Customer.getTotal_customer()) + "" );
        lblTotalGalleriesVal.setText( Gallery.getTotal_gallery() + "");
        lblTotalCarsVal.setText( Car.getTotal_id() + "" );
        lblTotalOrdersVal.setText( Order.getTotal_id() + "");
    }
    
    private void initializeUserInfo() {
        lblUserFullNameVal.setText( users.get( currentUserIndex ).getFullName() );
        lblUserGenderVal.setText( users.get( currentUserIndex ).getGender() );
        lblUserAgeVal.setText( users.get( currentUserIndex ).getAge() + "" );
        lblPhoneNumVal.setText( users.get( currentUserIndex ).getPhoneNumber() );
        lblUserNameVal.setText( users.get( currentUserIndex ).getUsername() );
    }
    
    private void lblBackgroundViewUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackgroundViewUsersMouseEntered
        // TODO add your handling code here:
        lblBackgroundViewUsers.setIcon( new ImageIcon(getClass().getResource("/images/purpleWhiteBackground220_165.png")));
    }//GEN-LAST:event_lblBackgroundViewUsersMouseEntered

    private void lblBackgroundViewUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackgroundViewUsersMouseExited
        // TODO add your handling code here:
        lblBackgroundViewUsers.setIcon( new ImageIcon(getClass().getResource("/images/white220_165.png")));
    }//GEN-LAST:event_lblBackgroundViewUsersMouseExited

    private void lblBackgroundAddGalOwnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackgroundAddGalOwnMouseEntered
        // TODO add your handling code here:
        lblBackgroundAddGalOwn.setIcon( new ImageIcon(getClass().getResource("/images/purpleWhiteBackground220_165.png")));
    }//GEN-LAST:event_lblBackgroundAddGalOwnMouseEntered

    private void lblBackgroundAddGalOwnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackgroundAddGalOwnMouseExited
        // TODO add your handling code here:
        lblBackgroundAddGalOwn.setIcon( new ImageIcon(getClass().getResource("/images/white220_165.png")));
    }//GEN-LAST:event_lblBackgroundAddGalOwnMouseExited

    private void lblBackgroundViewOrdersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackgroundViewOrdersMouseEntered
        // TODO add your handling code here:
        lblBackgroundViewOrders.setIcon( new ImageIcon(getClass().getResource("/images/purpleWhiteBackground220_165.png")));
    }//GEN-LAST:event_lblBackgroundViewOrdersMouseEntered

    private void lblBackgroundViewOrdersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackgroundViewOrdersMouseExited
        // TODO add your handling code here:
        lblBackgroundViewOrders.setIcon( new ImageIcon(getClass().getResource("/images/white220_165.png")));
    }//GEN-LAST:event_lblBackgroundViewOrdersMouseExited

    private void lblBackgroundViewCarsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackgroundViewCarsMouseEntered
        // TODO add your handling code here:
        lblBackgroundViewCars.setIcon( new ImageIcon(getClass().getResource("/images/purpleWhiteBackground220_165.png")));
    }//GEN-LAST:event_lblBackgroundViewCarsMouseEntered

    private void lblBackgroundViewCarsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackgroundViewCarsMouseExited
        // TODO add your handling code here:
        lblBackgroundViewCars.setIcon( new ImageIcon(getClass().getResource("/images/white220_165.png")));
    }//GEN-LAST:event_lblBackgroundViewCarsMouseExited

    private void lblExitColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitColorMouseClicked
        // TODO add your handling code here:
        System.exit( 0 );
    }//GEN-LAST:event_lblExitColorMouseClicked

    private void lblExitColorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitColorMouseEntered
        // TODO add your handling code here:
        lblExitColor.setIcon( new ImageIcon(getClass().getResource("/images/pnlExitBackground.png")));
    }//GEN-LAST:event_lblExitColorMouseEntered

    private void lblExitColorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitColorMouseExited
        // TODO add your handling code here:
        lblExitColor.setIcon( new ImageIcon());
    }//GEN-LAST:event_lblExitColorMouseExited

    private void lblSimpleHomeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSimpleHomeIconMouseClicked
        // TODO add your handling code here:
        HelperMethods.changePage(pnlHome, layerPnl);
    }//GEN-LAST:event_lblSimpleHomeIconMouseClicked

    private void lblBackgroundViewUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackgroundViewUsersMouseClicked
        // TODO add your handling code here:
        HelperMethods.changePage(pnlShowUsers, layerPnl);
    }//GEN-LAST:event_lblBackgroundViewUsersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane layerPnl;
    private javax.swing.JLabel lblAddGalleryOwner;
    private javax.swing.JLabel lblAddGalleryOwnerIcon;
    private javax.swing.JLabel lblAdminBackground2;
    private javax.swing.JLabel lblAdminIcon;
    private javax.swing.JLabel lblAdminIconBackground;
    private javax.swing.JLabel lblAppInf;
    private javax.swing.JLabel lblBackgroundAddGalOwn;
    private javax.swing.JLabel lblBackgroundViewCars;
    private javax.swing.JLabel lblBackgroundViewOrders;
    private javax.swing.JLabel lblBackgroundViewUsers;
    private javax.swing.JLabel lblExitColor;
    private javax.swing.JLabel lblExitIcon;
    private javax.swing.JLabel lblExitText;
    private javax.swing.JLabel lblLeftPnlBackground;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblMailVal;
    private javax.swing.JLabel lblPhoneNum;
    private javax.swing.JLabel lblPhoneNumVal;
    private javax.swing.JLabel lblProfilePic;
    private javax.swing.JLabel lblSimpleHomeIcon;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalCars;
    private javax.swing.JLabel lblTotalCarsVal;
    private javax.swing.JLabel lblTotalCust;
    private javax.swing.JLabel lblTotalCustVal;
    private javax.swing.JLabel lblTotalGalOwn;
    private javax.swing.JLabel lblTotalGalOwnVal;
    private javax.swing.JLabel lblTotalGalleries;
    private javax.swing.JLabel lblTotalGalleriesVal;
    private javax.swing.JLabel lblTotalOrder;
    private javax.swing.JLabel lblTotalOrderVal;
    private javax.swing.JLabel lblTotalOrders;
    private javax.swing.JLabel lblTotalOrdersVal;
    private javax.swing.JLabel lblUserAge;
    private javax.swing.JLabel lblUserAgeVal;
    private javax.swing.JLabel lblUserBg1;
    private javax.swing.JLabel lblUserBg2;
    private javax.swing.JLabel lblUserFullName;
    private javax.swing.JLabel lblUserFullNameVal;
    private javax.swing.JLabel lblUserGender;
    private javax.swing.JLabel lblUserGenderVal;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserName1;
    private javax.swing.JLabel lblUserNameVal;
    private javax.swing.JLabel lblUserNameVal1;
    private javax.swing.JLabel lblViewCars;
    private javax.swing.JLabel lblViewCarsIcon;
    private javax.swing.JLabel lblViewOrders;
    private javax.swing.JLabel lblViewOrdersIcon;
    private javax.swing.JLabel lblViewUsers;
    private javax.swing.JLabel lblViewUsersIcon;
    private javax.swing.JPanel pnlAddGalleryOwner;
    private javax.swing.JPanel pnlExit;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlParent;
    private javax.swing.JPanel pnlShowUsers;
    private javax.swing.JPanel pnlViewCars;
    private javax.swing.JPanel pnlViewOrders;
    private javax.swing.JPanel pnlViewUsers;
    // End of variables declaration//GEN-END:variables
}
