/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Business.RentCarSystem;
import Entities.Concrete.Order;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lian La-Fey
 */
public final class Bill extends javax.swing.JFrame {

    /**
     * Creates new form Bill
     */
    
    private Order order;
    
    public Bill(Order order) {
        initComponents();
        this.order = order;
        initializeFields();
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setBackground( new Color(255, 255, 255));
        centerRenderer.setHorizontalAlignment( SwingConstants.CENTER );
        orderTable.setDefaultRenderer(Object.class, centerRenderer);
        orderTable.getTableHeader().setDefaultRenderer( new DefaultTableCellRenderer(){
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                setFont( new Font("Tahoma", Font.BOLD, 12) );
                setBackground( new Color(59, 78, 135) );
                setForeground( new Color(255, 255, 255) );
                setHorizontalAlignment(CENTER);
                return this;
            }
            
        });
        jScrollPane1.setBackground( new Color(255, 255, 255) );
        jScrollPane1.getViewport().setBackground( new Color(255, 255, 255) );
        jScrollPane1.setOpaque( true );
    }
    
    private void initializeFields() {
        lblPhoneNumGalleryOwnValue.setText( order.getPhoneNumber() );
        Date date = new Date();
        tbxDate.setText( date.toString().substring(0, 11 ) + date.toString().substring( order.getRentDate().length() - 4) );
        tbxOrderID.setText( "" + order.getOrderId() );
        tbxCustımerID.setText( "" + order.getCustomerId() );
        lblPickUpDateValue.setText( order.getRentDate().substring(0, 11 ) +  order.getRentDate().substring( order.getRentDate().length() - 4 ));
        lblReturnDateValue.setText( order.getReturnDate().substring(0, 11 ) + order.getReturnDate().substring( order.getRentDate().length() - 4 ));
        lblSubTotalValue.setText( String.format("$%.2f", order.getAmountPaid()) );
        lblDiscountValue.setText( String.format("$%.2f", order.getAmountPaid() * RentCarSystem.getPromotionCodeByCode(order.getPromotionCodeId()).getDiscount() ) );
        lblTotalValue.setText( String.format("$%.2f",order.getAmountPaid() - order.getAmountPaid() * RentCarSystem.getPromotionCodeByCode(order.getPromotionCodeId()).getDiscount() ) );
        
        DefaultTableModel tableModel = (DefaultTableModel) orderTable.getModel();
        tableModel.setRowCount( 0 );
        
        tableModel.addRow( new Object[]{order.getGalleryId(), order.getBrand() + " " + order.getModel(), });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_invoice = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblOrderID = new javax.swing.JLabel();
        lblCustomerID = new javax.swing.JLabel();
        tbxDate = new javax.swing.JTextField();
        tbxOrderID = new javax.swing.JTextField();
        tbxCustımerID = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lblCompanyLogo = new javax.swing.JLabel();
        lblStreetAddress = new javax.swing.JLabel();
        lblStreetAddressValue = new javax.swing.JLabel();
        lblTownCity = new javax.swing.JLabel();
        lblTownCityValue = new javax.swing.JLabel();
        lblPhoneNumGalleryOwn = new javax.swing.JLabel();
        lblPhoneNumGalleryOwnValue = new javax.swing.JLabel();
        lblWebsite = new javax.swing.JLabel();
        lblWebsiteValue = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblBillTo = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblNameValue = new javax.swing.JLabel();
        lblCustomerPhoneNum = new javax.swing.JLabel();
        lblCustomerPhoneNumValue = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        lblSubTotal = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblSubTotalValue = new javax.swing.JLabel();
        lblDiscountValue = new javax.swing.JLabel();
        lblTotalValue = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        lblDateRanges = new javax.swing.JLabel();
        lblPickUpDate = new javax.swing.JLabel();
        lblPickUpDateValue = new javax.swing.JLabel();
        lblReturnDate = new javax.swing.JLabel();
        lblReturnDateValue = new javax.swing.JLabel();
        closeIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lbl_invoice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_invoice.setForeground(new java.awt.Color(59, 78, 135));
        lbl_invoice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_invoice.setText("INVOICE");

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDate.setText("Date");

        lblOrderID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblOrderID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOrderID.setText("Order ID");

        lblCustomerID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCustomerID.setText("Customer ID");

        tbxDate.setEditable(false);
        tbxDate.setBackground(new java.awt.Color(255, 255, 255));
        tbxDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbxDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tbxDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbxDate.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        tbxOrderID.setEditable(false);
        tbxOrderID.setBackground(new java.awt.Color(255, 255, 255));
        tbxOrderID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbxOrderID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tbxOrderID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbxOrderID.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        tbxCustımerID.setEditable(false);
        tbxCustımerID.setBackground(new java.awt.Color(255, 255, 255));
        tbxCustımerID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbxCustımerID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tbxCustımerID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbxCustımerID.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCustomerID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbxOrderID)
                            .addComponent(tbxCustımerID, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(tbxDate))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lbl_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxCustımerID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblCompanyLogo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCompanyLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompanyLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoSmall.png"))); // NOI18N

        lblStreetAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblStreetAddress.setText("Street Address : ");

        lblStreetAddressValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblStreetAddressValue.setForeground(new java.awt.Color(0, 0, 102));
        lblStreetAddressValue.setText("Kavaklıdere, Tunus Cd. No:71 D:2, 06680");

        lblTownCity.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTownCity.setText("Town City        : ");

        lblTownCityValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTownCityValue.setForeground(new java.awt.Color(0, 0, 102));
        lblTownCityValue.setText("Çankaya/Ankara");

        lblPhoneNumGalleryOwn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPhoneNumGalleryOwn.setText("Phone Number : ");

        lblPhoneNumGalleryOwnValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPhoneNumGalleryOwnValue.setForeground(new java.awt.Color(0, 0, 102));
        lblPhoneNumGalleryOwnValue.setText("gallery owner phone number");

        lblWebsite.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblWebsite.setText("Website           : ");

        lblWebsiteValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblWebsiteValue.setForeground(new java.awt.Color(0, 0, 102));
        lblWebsiteValue.setText("https://www.hertz.com.tr/");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblWebsite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblWebsiteValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblCompanyLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblStreetAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStreetAddressValue))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblTownCity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTownCityValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblPhoneNumGalleryOwn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPhoneNumGalleryOwnValue, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCompanyLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreetAddress)
                    .addComponent(lblStreetAddressValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTownCity)
                    .addComponent(lblTownCityValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumGalleryOwn)
                    .addComponent(lblPhoneNumGalleryOwnValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWebsite)
                    .addComponent(lblWebsiteValue))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lblBillTo.setBackground(new java.awt.Color(59, 78, 135));
        lblBillTo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBillTo.setForeground(new java.awt.Color(255, 255, 255));
        lblBillTo.setText("BILL TO :");
        lblBillTo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        lblBillTo.setOpaque(true);

        lblName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblName.setText("Name               : ");

        lblNameValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNameValue.setForeground(new java.awt.Color(0, 0, 102));
        lblNameValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameValue.setText("fullName");

        lblCustomerPhoneNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCustomerPhoneNum.setText("Phone Number : ");

        lblCustomerPhoneNumValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCustomerPhoneNumValue.setForeground(new java.awt.Color(0, 0, 102));
        lblCustomerPhoneNumValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustomerPhoneNumValue.setText("phoneNum");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCustomerPhoneNum, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNameValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCustomerPhoneNumValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblBillTo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblBillTo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCustomerPhoneNum))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblNameValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCustomerPhoneNumValue)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        orderTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CAR ID", "DESCRIPTION", "TOTAL DAY", "DAILY PRICE", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderTable.setFocusable(false);
        orderTable.setGridColor(new java.awt.Color(128, 128, 128));
        orderTable.setOpaque(false);
        orderTable.setRowHeight(30);
        orderTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        orderTable.setShowGrid(true);
        orderTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(orderTable);
        if (orderTable.getColumnModel().getColumnCount() > 0) {
            orderTable.getColumnModel().getColumn(0).setPreferredWidth(75);
            orderTable.getColumnModel().getColumn(0).setMaxWidth(75);
            orderTable.getColumnModel().getColumn(1).setResizable(false);
            orderTable.getColumnModel().getColumn(1).setPreferredWidth(60);
            orderTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            orderTable.getColumnModel().getColumn(2).setMaxWidth(100);
            orderTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            orderTable.getColumnModel().getColumn(3).setMaxWidth(100);
            orderTable.getColumnModel().getColumn(4).setResizable(false);
            orderTable.getColumnModel().getColumn(4).setPreferredWidth(25);
        }

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 778, 90));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        lblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSubTotal.setText("SUB TOTAL");

        lblDiscount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDiscount.setText("DISCOUNT");

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotal.setText("TOTAL");

        lblSubTotalValue.setBackground(new java.awt.Color(250, 250, 250));
        lblSubTotalValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSubTotalValue.setForeground(new java.awt.Color(51, 153, 0));
        lblSubTotalValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubTotalValue.setText("$173.25");
        lblSubTotalValue.setOpaque(true);

        lblDiscountValue.setBackground(new java.awt.Color(250, 250, 250));
        lblDiscountValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDiscountValue.setForeground(new java.awt.Color(204, 0, 51));
        lblDiscountValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiscountValue.setText("$25.45");
        lblDiscountValue.setOpaque(true);

        lblTotalValue.setBackground(new java.awt.Color(250, 250, 250));
        lblTotalValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalValue.setForeground(new java.awt.Color(51, 153, 0));
        lblTotalValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalValue.setText("$147,8");
        lblTotalValue.setOpaque(true);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addComponent(lblDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblDiscountValue, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblSubTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiscountValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        lblDateRanges.setBackground(new java.awt.Color(59, 78, 135));
        lblDateRanges.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDateRanges.setForeground(new java.awt.Color(255, 255, 255));
        lblDateRanges.setText("Date Ranges :");
        lblDateRanges.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        lblDateRanges.setOpaque(true);

        lblPickUpDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPickUpDate.setText("Pick-Up Date : ");

        lblPickUpDateValue.setBackground(new java.awt.Color(255, 255, 255));
        lblPickUpDateValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPickUpDateValue.setForeground(new java.awt.Color(0, 0, 102));
        lblPickUpDateValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPickUpDateValue.setText(" ");
        lblPickUpDateValue.setOpaque(true);

        lblReturnDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblReturnDate.setText("Return Date : ");

        lblReturnDateValue.setBackground(new java.awt.Color(255, 255, 255));
        lblReturnDateValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblReturnDateValue.setForeground(new java.awt.Color(0, 0, 102));
        lblReturnDateValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReturnDateValue.setText(" ");
        lblReturnDateValue.setOpaque(true);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDateRanges, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblReturnDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPickUpDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblReturnDateValue, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(lblPickUpDateValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblDateRanges, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPickUpDateValue)
                    .addComponent(lblPickUpDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReturnDateValue)
                    .addComponent(lblReturnDate))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        closeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close32.png"))); // NOI18N
        closeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(closeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeIconMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeIcon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBillTo;
    private javax.swing.JLabel lblCompanyLogo;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblCustomerPhoneNum;
    private javax.swing.JLabel lblCustomerPhoneNumValue;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDateRanges;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblDiscountValue;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameValue;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JLabel lblPhoneNumGalleryOwn;
    private javax.swing.JLabel lblPhoneNumGalleryOwnValue;
    private javax.swing.JLabel lblPickUpDate;
    private javax.swing.JLabel lblPickUpDateValue;
    private javax.swing.JLabel lblReturnDate;
    private javax.swing.JLabel lblReturnDateValue;
    private javax.swing.JLabel lblStreetAddress;
    private javax.swing.JLabel lblStreetAddressValue;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblSubTotalValue;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalValue;
    private javax.swing.JLabel lblTownCity;
    private javax.swing.JLabel lblTownCityValue;
    private javax.swing.JLabel lblWebsite;
    private javax.swing.JLabel lblWebsiteValue;
    private javax.swing.JLabel lbl_invoice;
    private javax.swing.JTable orderTable;
    private javax.swing.JTextField tbxCustımerID;
    private javax.swing.JTextField tbxDate;
    private javax.swing.JTextField tbxOrderID;
    // End of variables declaration//GEN-END:variables
}
