package GUI;


import java.awt.Color;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Asus
 */
public class CustomerPage extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public CustomerPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlParent = new javax.swing.JPanel();
        PnlLeftSide = new javax.swing.JPanel();
        pnlProfile = new javax.swing.JPanel();
        lblProfile = new javax.swing.JLabel();
        pnlHomePage = new javax.swing.JPanel();
        lblHomePage = new javax.swing.JLabel();
        pnlExit = new javax.swing.JPanel();
        lblSignOut = new javax.swing.JLabel();
        pnlProfileInfo = new javax.swing.JPanel();
        lblProfilePic = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblUserMail = new javax.swing.JLabel();
        lblTheUserMail = new javax.swing.JLabel();
        lblTheUserName = new javax.swing.JLabel();
        pnlLayered = new javax.swing.JLayeredPane();
        pnlLayeredProfile = new javax.swing.JPanel();
        pnlInPnlLayerdProfileFilter = new javax.swing.JPanel();
        lblOrderPrice = new javax.swing.JLabel();
        cbxOrderPrice = new javax.swing.JComboBox<>();
        lblOrderGallery = new javax.swing.JLabel();
        cbxOrderGalery = new javax.swing.JComboBox<>();
        lblRange1 = new javax.swing.JLabel();
        tbxMin1 = new javax.swing.JTextField();
        tbxMax1 = new javax.swing.JTextField();
        btnFilterOrders = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listOrders = new javax.swing.JList<>();
        pnlInLayeredHomePageCarInfo1 = new javax.swing.JPanel();
        lblOrderdCarImage = new javax.swing.JLabel();
        lblOrderedCarBrand = new javax.swing.JLabel();
        lblOrderedCarMoedl = new javax.swing.JLabel();
        lblOrderedCarDate = new javax.swing.JLabel();
        lblOrderedCarPrice = new javax.swing.JLabel();
        lblOrderedCarGallery = new javax.swing.JLabel();
        lblOrderedCarBrandValue = new javax.swing.JLabel();
        lblOrderedCarModelValue = new javax.swing.JLabel();
        lblOrderedCarDateValue = new javax.swing.JLabel();
        lblOrderedCarGalleryValue = new javax.swing.JLabel();
        lblOrderedCarPriceValue = new javax.swing.JLabel();
        btnNextOrder = new javax.swing.JButton();
        btnPreviousOrder = new javax.swing.JButton();
        btnDeleteOrder = new javax.swing.JButton();
        pnlUserInformation = new javax.swing.JPanel();
        lblUserName1 = new javax.swing.JLabel();
        lblUserGender = new javax.swing.JLabel();
        lblUserAge = new javax.swing.JLabel();
        lblUserEmail = new javax.swing.JLabel();
        lblUserFullName = new javax.swing.JLabel();
        tbxUserName = new javax.swing.JTextField();
        tbxUserFullName = new javax.swing.JTextField();
        tbxUserGender = new javax.swing.JTextField();
        tbxUserAge = new javax.swing.JTextField();
        tbxUserEmail = new javax.swing.JTextField();
        pnlUserBankInformation = new javax.swing.JPanel();
        lblUserCurrentCash = new javax.swing.JLabel();
        lblUserCurrentCashValue = new javax.swing.JLabel();
        lblUserCurrentCash1 = new javax.swing.JLabel();
        tbxDepositedCash = new javax.swing.JTextField();
        lblUserCurrentCash2 = new javax.swing.JLabel();
        lblUserTotalCash = new javax.swing.JLabel();
        btnUserDepositCash = new javax.swing.JButton();
        btnSaveChanges = new javax.swing.JButton();
        btnModifyUser = new javax.swing.JButton();
        lblUserProfileImage = new javax.swing.JLabel();
        btnDeleteUser = new javax.swing.JButton();
        pnlLayeredHomePage = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCars = new javax.swing.JList<>();
        pnlInPnlLayerdHomePagefilter = new javax.swing.JPanel();
        lblPrice = new javax.swing.JLabel();
        cbxPrice = new javax.swing.JComboBox<>();
        lblGallery = new javax.swing.JLabel();
        cbxGallery = new javax.swing.JComboBox<>();
        lblRange = new javax.swing.JLabel();
        tbxMin = new javax.swing.JTextField();
        tbxMax = new javax.swing.JTextField();
        btnFilter = new javax.swing.JButton();
        pnlInLayeredHomePageCarInfo = new javax.swing.JPanel();
        lblCarImage = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblCarPrice = new javax.swing.JLabel();
        lblKm = new javax.swing.JLabel();
        lblBrandOfCar = new javax.swing.JLabel();
        lblModelOfCar = new javax.swing.JLabel();
        lblYearOfCar = new javax.swing.JLabel();
        lblKmOfCar = new javax.swing.JLabel();
        lblPriceOfCar = new javax.swing.JLabel();
        btnNextCar = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnRent = new javax.swing.JButton();
        pnlApproval = new javax.swing.JPanel();
        btnApprove1 = new javax.swing.JButton();
        lblTotalCashAfterRental = new javax.swing.JLabel();
        spnDay = new javax.swing.JSpinner();
        lblCurrentCash1 = new javax.swing.JLabel();
        lblTotalCashAfterRentalOfUser = new javax.swing.JLabel();
        lblCurrentCash2 = new javax.swing.JLabel();
        lblCurrentCashOfUser = new javax.swing.JLabel();
        lblTotalPaymentOfUser = new javax.swing.JLabel();
        lblTotalPayment1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlLeftSide.setBackground(new java.awt.Color(202, 207, 210));

        pnlProfile.setBackground(new java.awt.Color(211, 84, 0));
        pnlProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlProfileMouseClicked(evt);
            }
        });

        lblProfile.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblProfile.setForeground(new java.awt.Color(255, 255, 255));
        lblProfile.setText("Profile");
        lblProfile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlProfileLayout = new javax.swing.GroupLayout(pnlProfile);
        pnlProfile.setLayout(pnlProfileLayout);
        pnlProfileLayout.setHorizontalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfileLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(lblProfile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlProfileLayout.setVerticalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        pnlHomePage.setBackground(new java.awt.Color(211, 84, 0));
        pnlHomePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlHomePageMouseClicked(evt);
            }
        });

        lblHomePage.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblHomePage.setForeground(new java.awt.Color(255, 255, 255));
        lblHomePage.setText("Home Page");
        lblHomePage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlHomePageLayout = new javax.swing.GroupLayout(pnlHomePage);
        pnlHomePage.setLayout(pnlHomePageLayout);
        pnlHomePageLayout.setHorizontalGroup(
            pnlHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomePageLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lblHomePage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHomePageLayout.setVerticalGroup(
            pnlHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHomePage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        pnlExit.setBackground(new java.awt.Color(211, 84, 0));

        lblSignOut.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblSignOut.setForeground(new java.awt.Color(255, 255, 255));
        lblSignOut.setText("Sign Out");
        lblSignOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlExitLayout = new javax.swing.GroupLayout(pnlExit);
        pnlExit.setLayout(pnlExitLayout);
        pnlExitLayout.setHorizontalGroup(
            pnlExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExitLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(lblSignOut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlExitLayout.setVerticalGroup(
            pnlExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSignOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        pnlProfileInfo.setBackground(new java.awt.Color(133, 146, 158));

        lblUserName.setBackground(new java.awt.Color(242, 243, 244));
        lblUserName.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(208, 211, 212));
        lblUserName.setText("User Name");

        lblUserMail.setBackground(new java.awt.Color(242, 243, 244));
        lblUserMail.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblUserMail.setForeground(new java.awt.Color(208, 211, 212));
        lblUserMail.setText("Mail");

        lblTheUserMail.setBackground(new java.awt.Color(242, 243, 244));
        lblTheUserMail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTheUserMail.setForeground(new java.awt.Color(153, 51, 255));

        lblTheUserName.setBackground(new java.awt.Color(242, 243, 244));
        lblTheUserName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTheUserName.setForeground(new java.awt.Color(153, 51, 255));

        javax.swing.GroupLayout pnlProfileInfoLayout = new javax.swing.GroupLayout(pnlProfileInfo);
        pnlProfileInfo.setLayout(pnlProfileInfoLayout);
        pnlProfileInfoLayout.setHorizontalGroup(
            pnlProfileInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfileInfoLayout.createSequentialGroup()
                .addGroup(pnlProfileInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlProfileInfoLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlProfileInfoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnlProfileInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserName)
                            .addComponent(lblUserMail, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlProfileInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTheUserMail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTheUserName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        pnlProfileInfoLayout.setVerticalGroup(
            pnlProfileInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfileInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(pnlProfileInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserName)
                    .addComponent(lblTheUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProfileInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUserMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTheUserMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PnlLeftSideLayout = new javax.swing.GroupLayout(PnlLeftSide);
        PnlLeftSide.setLayout(PnlLeftSideLayout);
        PnlLeftSideLayout.setHorizontalGroup(
            PnlLeftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlHomePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlProfileInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PnlLeftSideLayout.setVerticalGroup(
            PnlLeftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlLeftSideLayout.createSequentialGroup()
                .addComponent(pnlProfileInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(pnlHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(pnlExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pnlLayered.setLayout(new java.awt.CardLayout());

        pnlInPnlLayerdProfileFilter.setBackground(new java.awt.Color(242, 243, 244));
        pnlInPnlLayerdProfileFilter.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15), new java.awt.Color(255, 102, 0))); // NOI18N

        lblOrderPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOrderPrice.setText("    Price:");

        cbxOrderPrice.setBackground(new java.awt.Color(242, 243, 244));
        cbxOrderPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbxOrderPrice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascending", "Descending" }));

        lblOrderGallery.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOrderGallery.setText("  Gallery:");

        cbxOrderGalery.setBackground(new java.awt.Color(242, 243, 244));
        cbxOrderGalery.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbxOrderGalery.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));

        lblRange1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRange1.setText("  Range:");

        tbxMin1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbxMin1.setText("      Min");

        tbxMax1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbxMax1.setText("     Max");

        btnFilterOrders.setBackground(new java.awt.Color(211, 84, 0));
        btnFilterOrders.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFilterOrders.setText("Filter");

        javax.swing.GroupLayout pnlInPnlLayerdProfileFilterLayout = new javax.swing.GroupLayout(pnlInPnlLayerdProfileFilter);
        pnlInPnlLayerdProfileFilter.setLayout(pnlInPnlLayerdProfileFilterLayout);
        pnlInPnlLayerdProfileFilterLayout.setHorizontalGroup(
            pnlInPnlLayerdProfileFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInPnlLayerdProfileFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOrderPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxOrderPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblRange1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbxMin1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbxMax1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblOrderGallery, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxOrderGalery, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnFilterOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        pnlInPnlLayerdProfileFilterLayout.setVerticalGroup(
            pnlInPnlLayerdProfileFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInPnlLayerdProfileFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInPnlLayerdProfileFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrderGallery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxOrderPrice)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInPnlLayerdProfileFilterLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFilterOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tbxMin1)
                    .addComponent(tbxMax1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlInPnlLayerdProfileFilterLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(pnlInPnlLayerdProfileFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrderPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRange1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(cbxOrderGalery, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        listOrders.setBackground(new java.awt.Color(202, 207, 210));
        listOrders.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Orders", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15), new java.awt.Color(255, 102, 0))); // NOI18N
        listOrders.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jScrollPane2.setViewportView(listOrders);

        pnlInLayeredHomePageCarInfo1.setBackground(new java.awt.Color(202, 207, 210));
        pnlInLayeredHomePageCarInfo1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Order Detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15), new java.awt.Color(255, 102, 0))); // NOI18N

        lblOrderedCarBrand.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOrderedCarBrand.setText("  Brand:");

        lblOrderedCarMoedl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOrderedCarMoedl.setText("  Model:");

        lblOrderedCarDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOrderedCarDate.setText("  Date:");

        lblOrderedCarPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOrderedCarPrice.setText("  Price:");

        lblOrderedCarGallery.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOrderedCarGallery.setText("  Gallery:");

        lblOrderedCarBrandValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblOrderedCarModelValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblOrderedCarDateValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblOrderedCarGalleryValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblOrderedCarPriceValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnNextOrder.setBackground(new java.awt.Color(211, 84, 0));
        btnNextOrder.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnNextOrder.setText("Next");

        btnPreviousOrder.setBackground(new java.awt.Color(211, 84, 0));
        btnPreviousOrder.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnPreviousOrder.setText("Previous");

        btnDeleteOrder.setBackground(new java.awt.Color(211, 84, 0));
        btnDeleteOrder.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnDeleteOrder.setText("Delete");

        javax.swing.GroupLayout pnlInLayeredHomePageCarInfo1Layout = new javax.swing.GroupLayout(pnlInLayeredHomePageCarInfo1);
        pnlInLayeredHomePageCarInfo1.setLayout(pnlInLayeredHomePageCarInfo1Layout);
        pnlInLayeredHomePageCarInfo1Layout.setHorizontalGroup(
            pnlInLayeredHomePageCarInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInLayeredHomePageCarInfo1Layout.createSequentialGroup()
                .addGroup(pnlInLayeredHomePageCarInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInLayeredHomePageCarInfo1Layout.createSequentialGroup()
                        .addComponent(lblOrderdCarImage, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlInLayeredHomePageCarInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlInLayeredHomePageCarInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblOrderedCarGallery, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblOrderedCarPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblOrderedCarDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrderedCarMoedl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrderedCarBrand, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlInLayeredHomePageCarInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrderedCarBrandValue, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrderedCarModelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrderedCarDateValue, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrderedCarGalleryValue, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrderedCarPriceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlInLayeredHomePageCarInfo1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPreviousOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNextOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(btnDeleteOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlInLayeredHomePageCarInfo1Layout.setVerticalGroup(
            pnlInLayeredHomePageCarInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInLayeredHomePageCarInfo1Layout.createSequentialGroup()
                .addGroup(pnlInLayeredHomePageCarInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblOrderdCarImage, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlInLayeredHomePageCarInfo1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlInLayeredHomePageCarInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblOrderedCarBrandValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOrderedCarBrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(pnlInLayeredHomePageCarInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrderedCarMoedl)
                            .addComponent(lblOrderedCarModelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(pnlInLayeredHomePageCarInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrderedCarDate)
                            .addComponent(lblOrderedCarDateValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlInLayeredHomePageCarInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOrderedCarGallery)
                            .addComponent(lblOrderedCarGalleryValue, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlInLayeredHomePageCarInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrderedCarPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOrderedCarPriceValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInLayeredHomePageCarInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPreviousOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNextOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnlUserInformation.setBackground(new java.awt.Color(202, 207, 210));
        pnlUserInformation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Accaunt Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15), new java.awt.Color(255, 102, 0))); // NOI18N

        lblUserName1.setBackground(new java.awt.Color(242, 243, 244));
        lblUserName1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserName1.setForeground(new java.awt.Color(51, 51, 51));
        lblUserName1.setText("User Name:");

        lblUserGender.setBackground(new java.awt.Color(242, 243, 244));
        lblUserGender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserGender.setForeground(new java.awt.Color(51, 51, 51));
        lblUserGender.setText("Gender:");

        lblUserAge.setBackground(new java.awt.Color(242, 243, 244));
        lblUserAge.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserAge.setForeground(new java.awt.Color(51, 51, 51));
        lblUserAge.setText("Age");

        lblUserEmail.setBackground(new java.awt.Color(242, 243, 244));
        lblUserEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserEmail.setForeground(new java.awt.Color(51, 51, 51));
        lblUserEmail.setText("Email");

        lblUserFullName.setBackground(new java.awt.Color(242, 243, 244));
        lblUserFullName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserFullName.setForeground(new java.awt.Color(51, 51, 51));
        lblUserFullName.setText("Full Name");

        tbxUserName.setEnabled(false);

        tbxUserFullName.setEnabled(false);

        tbxUserGender.setEnabled(false);

        tbxUserAge.setEnabled(false);

        tbxUserEmail.setEnabled(false);

        pnlUserBankInformation.setBackground(new java.awt.Color(202, 207, 210));
        pnlUserBankInformation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bank Account Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15), new java.awt.Color(255, 102, 0))); // NOI18N

        lblUserCurrentCash.setBackground(new java.awt.Color(242, 243, 244));
        lblUserCurrentCash.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserCurrentCash.setForeground(new java.awt.Color(51, 51, 51));
        lblUserCurrentCash.setText("Current Cash:");

        lblUserCurrentCashValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblUserCurrentCash1.setBackground(new java.awt.Color(242, 243, 244));
        lblUserCurrentCash1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserCurrentCash1.setForeground(new java.awt.Color(51, 51, 51));
        lblUserCurrentCash1.setText("Deposited Cash:");

        lblUserCurrentCash2.setBackground(new java.awt.Color(242, 243, 244));
        lblUserCurrentCash2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserCurrentCash2.setForeground(new java.awt.Color(51, 51, 51));
        lblUserCurrentCash2.setText("Total Cash: ");

        lblUserTotalCash.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnUserDepositCash.setBackground(new java.awt.Color(211, 84, 0));
        btnUserDepositCash.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnUserDepositCash.setText("Deposit Cash");

        javax.swing.GroupLayout pnlUserBankInformationLayout = new javax.swing.GroupLayout(pnlUserBankInformation);
        pnlUserBankInformation.setLayout(pnlUserBankInformationLayout);
        pnlUserBankInformationLayout.setHorizontalGroup(
            pnlUserBankInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserBankInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUserBankInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUserBankInformationLayout.createSequentialGroup()
                        .addGroup(pnlUserBankInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserCurrentCash, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUserCurrentCash1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlUserBankInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbxDepositedCash, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(lblUserCurrentCashValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlUserBankInformationLayout.createSequentialGroup()
                        .addComponent(lblUserCurrentCash2)
                        .addGap(62, 62, 62)
                        .addComponent(lblUserTotalCash, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserBankInformationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUserDepositCash, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        pnlUserBankInformationLayout.setVerticalGroup(
            pnlUserBankInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserBankInformationLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlUserBankInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUserCurrentCashValue, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserCurrentCash, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlUserBankInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUserCurrentCash1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(tbxDepositedCash))
                .addGap(18, 18, 18)
                .addGroup(pnlUserBankInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUserBankInformationLayout.createSequentialGroup()
                        .addComponent(lblUserCurrentCash2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addGap(33, 33, 33))
                    .addGroup(pnlUserBankInformationLayout.createSequentialGroup()
                        .addComponent(lblUserTotalCash, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btnUserDepositCash, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnSaveChanges.setBackground(new java.awt.Color(211, 84, 0));
        btnSaveChanges.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnSaveChanges.setText("Save Changes");

        btnModifyUser.setBackground(new java.awt.Color(211, 84, 0));
        btnModifyUser.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnModifyUser.setText("Modify Account");

        btnDeleteUser.setBackground(new java.awt.Color(211, 84, 0));
        btnDeleteUser.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnDeleteUser.setText("Delete Account");

        javax.swing.GroupLayout pnlUserInformationLayout = new javax.swing.GroupLayout(pnlUserInformation);
        pnlUserInformation.setLayout(pnlUserInformationLayout);
        pnlUserInformationLayout.setHorizontalGroup(
            pnlUserInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUserInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUserInformationLayout.createSequentialGroup()
                        .addGroup(pnlUserInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUserInformationLayout.createSequentialGroup()
                                .addComponent(lblUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tbxUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlUserInformationLayout.createSequentialGroup()
                                .addComponent(lblUserFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tbxUserFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlUserInformationLayout.createSequentialGroup()
                                .addGroup(pnlUserInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUserGender, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUserAge, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUserEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlUserInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbxUserAge, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbxUserGender, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbxUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(50, 50, 50)
                        .addComponent(lblUserProfileImage, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUserInformationLayout.createSequentialGroup()
                        .addComponent(btnModifyUser, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveChanges)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlUserBankInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlUserInformationLayout.setVerticalGroup(
            pnlUserInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUserInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlUserBankInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlUserInformationLayout.createSequentialGroup()
                        .addGroup(pnlUserInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUserInformationLayout.createSequentialGroup()
                                .addGroup(pnlUserInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tbxUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUserName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlUserInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tbxUserFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUserFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlUserInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUserGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnlUserInformationLayout.createSequentialGroup()
                                        .addComponent(tbxUserGender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlUserInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblUserAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tbxUserAge, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlUserInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tbxUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblUserProfileImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlUserInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModifyUser, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout pnlLayeredProfileLayout = new javax.swing.GroupLayout(pnlLayeredProfile);
        pnlLayeredProfile.setLayout(pnlLayeredProfileLayout);
        pnlLayeredProfileLayout.setHorizontalGroup(
            pnlLayeredProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInPnlLayerdProfileFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLayeredProfileLayout.createSequentialGroup()
                .addGroup(pnlLayeredProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlUserInformation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlLayeredProfileLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlInLayeredHomePageCarInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(2, 2, 2))
        );
        pnlLayeredProfileLayout.setVerticalGroup(
            pnlLayeredProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayeredProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInPnlLayerdProfileFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLayeredProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(pnlInLayeredHomePageCarInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlUserInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlLayered.add(pnlLayeredProfile, "card2");

        listCars.setBackground(new java.awt.Color(202, 207, 210));
        listCars.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Car List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15), new java.awt.Color(255, 102, 0))); // NOI18N
        listCars.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jScrollPane1.setViewportView(listCars);

        pnlInPnlLayerdHomePagefilter.setBackground(new java.awt.Color(242, 243, 244));
        pnlInPnlLayerdHomePagefilter.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15), new java.awt.Color(255, 102, 0))); // NOI18N

        lblPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrice.setText("    Price:");

        cbxPrice.setBackground(new java.awt.Color(242, 243, 244));
        cbxPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbxPrice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascending", "Descending" }));

        lblGallery.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGallery.setText("  Gallery:");

        cbxGallery.setBackground(new java.awt.Color(242, 243, 244));
        cbxGallery.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbxGallery.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));

        lblRange.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRange.setText("  Range:");

        tbxMin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbxMin.setText("      Min");

        tbxMax.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbxMax.setText("     Max");

        btnFilter.setBackground(new java.awt.Color(211, 84, 0));
        btnFilter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFilter.setText("Filter");

        javax.swing.GroupLayout pnlInPnlLayerdHomePagefilterLayout = new javax.swing.GroupLayout(pnlInPnlLayerdHomePagefilter);
        pnlInPnlLayerdHomePagefilter.setLayout(pnlInPnlLayerdHomePagefilterLayout);
        pnlInPnlLayerdHomePagefilterLayout.setHorizontalGroup(
            pnlInPnlLayerdHomePagefilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInPnlLayerdHomePagefilterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(lblRange, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbxMin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbxMax, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblGallery, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxGallery, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        pnlInPnlLayerdHomePagefilterLayout.setVerticalGroup(
            pnlInPnlLayerdHomePagefilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInPnlLayerdHomePagefilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInPnlLayerdHomePagefilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGallery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxPrice)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInPnlLayerdHomePagefilterLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tbxMin)
                    .addComponent(tbxMax, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlInPnlLayerdHomePagefilterLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cbxGallery, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlInLayeredHomePageCarInfo.setBackground(new java.awt.Color(202, 207, 210));
        pnlInLayeredHomePageCarInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Car Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(255, 102, 0))); // NOI18N

        lblBrand.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBrand.setText("  Brand:");

        lblModel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblModel.setText("  Model:");

        lblYear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblYear.setText("   Year:");

        lblCarPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCarPrice.setText("   Price:");

        lblKm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKm.setText("   Km:");

        lblBrandOfCar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblModelOfCar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblYearOfCar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblKmOfCar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblPriceOfCar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnNextCar.setBackground(new java.awt.Color(211, 84, 0));
        btnNextCar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnNextCar.setText("Next");

        btnPrevious.setBackground(new java.awt.Color(211, 84, 0));
        btnPrevious.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnPrevious.setText("Previous");

        btnRent.setBackground(new java.awt.Color(211, 84, 0));
        btnRent.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnRent.setText("Rent");

        javax.swing.GroupLayout pnlInLayeredHomePageCarInfoLayout = new javax.swing.GroupLayout(pnlInLayeredHomePageCarInfo);
        pnlInLayeredHomePageCarInfo.setLayout(pnlInLayeredHomePageCarInfoLayout);
        pnlInLayeredHomePageCarInfoLayout.setHorizontalGroup(
            pnlInLayeredHomePageCarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInLayeredHomePageCarInfoLayout.createSequentialGroup()
                .addGroup(pnlInLayeredHomePageCarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInLayeredHomePageCarInfoLayout.createSequentialGroup()
                        .addComponent(lblCarImage, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlInLayeredHomePageCarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlInLayeredHomePageCarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblKm, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCarPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblYear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBrand, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlInLayeredHomePageCarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBrandOfCar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModelOfCar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblYearOfCar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKmOfCar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPriceOfCar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlInLayeredHomePageCarInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNextCar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(btnRent, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlInLayeredHomePageCarInfoLayout.setVerticalGroup(
            pnlInLayeredHomePageCarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInLayeredHomePageCarInfoLayout.createSequentialGroup()
                .addGroup(pnlInLayeredHomePageCarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblCarImage, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlInLayeredHomePageCarInfoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlInLayeredHomePageCarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblBrandOfCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(pnlInLayeredHomePageCarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblModel)
                            .addComponent(lblModelOfCar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(pnlInLayeredHomePageCarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblYear)
                            .addComponent(lblYearOfCar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlInLayeredHomePageCarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKm)
                            .addComponent(lblKmOfCar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlInLayeredHomePageCarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCarPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPriceOfCar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInLayeredHomePageCarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRent, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNextCar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlApproval.setBackground(new java.awt.Color(202, 207, 210));
        pnlApproval.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Approval", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15), new java.awt.Color(255, 102, 0))); // NOI18N

        btnApprove1.setBackground(new java.awt.Color(211, 84, 0));
        btnApprove1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnApprove1.setText("Approve");

        lblTotalCashAfterRental.setBackground(new java.awt.Color(242, 243, 244));
        lblTotalCashAfterRental.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalCashAfterRental.setForeground(new java.awt.Color(51, 51, 51));
        lblTotalCashAfterRental.setText("Total Cash After Rental");

        spnDay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        spnDay.setModel(new javax.swing.SpinnerNumberModel(1, 1, 90, 1));

        lblCurrentCash1.setBackground(new java.awt.Color(242, 243, 244));
        lblCurrentCash1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCurrentCash1.setForeground(new java.awt.Color(51, 51, 51));
        lblCurrentCash1.setText("Your Current Cash");

        lblTotalCashAfterRentalOfUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblCurrentCash2.setBackground(new java.awt.Color(242, 243, 244));
        lblCurrentCash2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCurrentCash2.setForeground(new java.awt.Color(51, 51, 51));
        lblCurrentCash2.setText("Number Of Day");

        lblCurrentCashOfUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblTotalPaymentOfUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblTotalPayment1.setBackground(new java.awt.Color(242, 243, 244));
        lblTotalPayment1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalPayment1.setForeground(new java.awt.Color(51, 51, 51));
        lblTotalPayment1.setText("Total Payment");

        javax.swing.GroupLayout pnlApprovalLayout = new javax.swing.GroupLayout(pnlApproval);
        pnlApproval.setLayout(pnlApprovalLayout);
        pnlApprovalLayout.setHorizontalGroup(
            pnlApprovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlApprovalLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlApprovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlApprovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTotalCashAfterRental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCurrentCash2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalPayment1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblCurrentCash1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlApprovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTotalCashAfterRentalOfUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spnDay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(lblCurrentCashOfUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalPaymentOfUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlApprovalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnApprove1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        pnlApprovalLayout.setVerticalGroup(
            pnlApprovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlApprovalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlApprovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlApprovalLayout.createSequentialGroup()
                        .addComponent(lblCurrentCashOfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnDay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotalPaymentOfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(lblTotalCashAfterRentalOfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlApprovalLayout.createSequentialGroup()
                        .addComponent(lblCurrentCash1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCurrentCash2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotalPayment1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalCashAfterRental, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnApprove1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlLayeredHomePageLayout = new javax.swing.GroupLayout(pnlLayeredHomePage);
        pnlLayeredHomePage.setLayout(pnlLayeredHomePageLayout);
        pnlLayeredHomePageLayout.setHorizontalGroup(
            pnlLayeredHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayeredHomePageLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlLayeredHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlInLayeredHomePageCarInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlApproval, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
            .addComponent(pnlInPnlLayerdHomePagefilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlLayeredHomePageLayout.setVerticalGroup(
            pnlLayeredHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLayeredHomePageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInPnlLayerdHomePagefilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLayeredHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlLayeredHomePageLayout.createSequentialGroup()
                        .addComponent(pnlInLayeredHomePageCarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlApproval, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pnlLayered.add(pnlLayeredHomePage, "card3");

        javax.swing.GroupLayout PnlParentLayout = new javax.swing.GroupLayout(PnlParent);
        PnlParent.setLayout(PnlParentLayout);
        PnlParentLayout.setHorizontalGroup(
            PnlParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlParentLayout.createSequentialGroup()
                .addComponent(PnlLeftSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlLayered, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PnlParentLayout.setVerticalGroup(
            PnlParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlLeftSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlLayered)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlProfileMouseClicked
        switchPanel(pnlLayeredProfile);
        pnlProfile.setBackground(Color.GRAY.brighter());
        Color color = new Color(211,84,0);
        pnlHomePage.setBackground(color);
    }//GEN-LAST:event_pnlProfileMouseClicked

    private void pnlHomePageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHomePageMouseClicked
        switchPanel(pnlLayeredHomePage);
        pnlHomePage.setBackground(Color.GRAY.brighter());
        Color color = new Color(211,84,0);
        pnlProfile.setBackground(color);
    }//GEN-LAST:event_pnlHomePageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlLeftSide;
    private javax.swing.JPanel PnlParent;
    private javax.swing.JButton btnApprove1;
    private javax.swing.JButton btnDeleteOrder;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnFilterOrders;
    private javax.swing.JButton btnModifyUser;
    private javax.swing.JButton btnNextCar;
    private javax.swing.JButton btnNextOrder;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnPreviousOrder;
    private javax.swing.JButton btnRent;
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JButton btnUserDepositCash;
    private javax.swing.JComboBox<String> cbxGallery;
    private javax.swing.JComboBox<String> cbxOrderGalery;
    private javax.swing.JComboBox<String> cbxOrderPrice;
    private javax.swing.JComboBox<String> cbxPrice;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblBrandOfCar;
    private javax.swing.JLabel lblCarImage;
    private javax.swing.JLabel lblCarPrice;
    private javax.swing.JLabel lblCurrentCash1;
    private javax.swing.JLabel lblCurrentCash2;
    private javax.swing.JLabel lblCurrentCashOfUser;
    private javax.swing.JLabel lblGallery;
    private javax.swing.JLabel lblHomePage;
    private javax.swing.JLabel lblKm;
    private javax.swing.JLabel lblKmOfCar;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblModelOfCar;
    private javax.swing.JLabel lblOrderGallery;
    private javax.swing.JLabel lblOrderPrice;
    private javax.swing.JLabel lblOrderdCarImage;
    private javax.swing.JLabel lblOrderedCarBrand;
    private javax.swing.JLabel lblOrderedCarBrandValue;
    private javax.swing.JLabel lblOrderedCarDate;
    private javax.swing.JLabel lblOrderedCarDateValue;
    private javax.swing.JLabel lblOrderedCarGallery;
    private javax.swing.JLabel lblOrderedCarGalleryValue;
    private javax.swing.JLabel lblOrderedCarModelValue;
    private javax.swing.JLabel lblOrderedCarMoedl;
    private javax.swing.JLabel lblOrderedCarPrice;
    private javax.swing.JLabel lblOrderedCarPriceValue;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblPriceOfCar;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblProfilePic;
    private javax.swing.JLabel lblRange;
    private javax.swing.JLabel lblRange1;
    private javax.swing.JLabel lblSignOut;
    private javax.swing.JLabel lblTheUserMail;
    private javax.swing.JLabel lblTheUserName;
    private javax.swing.JLabel lblTotalCashAfterRental;
    private javax.swing.JLabel lblTotalCashAfterRentalOfUser;
    private javax.swing.JLabel lblTotalPayment1;
    private javax.swing.JLabel lblTotalPaymentOfUser;
    private javax.swing.JLabel lblUserAge;
    private javax.swing.JLabel lblUserCurrentCash;
    private javax.swing.JLabel lblUserCurrentCash1;
    private javax.swing.JLabel lblUserCurrentCash2;
    private javax.swing.JLabel lblUserCurrentCashValue;
    private javax.swing.JLabel lblUserEmail;
    private javax.swing.JLabel lblUserFullName;
    private javax.swing.JLabel lblUserGender;
    private javax.swing.JLabel lblUserMail;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserName1;
    private javax.swing.JLabel lblUserProfileImage;
    private javax.swing.JLabel lblUserTotalCash;
    private javax.swing.JLabel lblYear;
    private javax.swing.JLabel lblYearOfCar;
    private javax.swing.JList<String> listCars;
    private javax.swing.JList<String> listOrders;
    private javax.swing.JPanel pnlApproval;
    private javax.swing.JPanel pnlExit;
    private javax.swing.JPanel pnlHomePage;
    private javax.swing.JPanel pnlInLayeredHomePageCarInfo;
    private javax.swing.JPanel pnlInLayeredHomePageCarInfo1;
    private javax.swing.JPanel pnlInPnlLayerdHomePagefilter;
    private javax.swing.JPanel pnlInPnlLayerdProfileFilter;
    private javax.swing.JLayeredPane pnlLayered;
    private javax.swing.JPanel pnlLayeredHomePage;
    private javax.swing.JPanel pnlLayeredProfile;
    private javax.swing.JPanel pnlProfile;
    private javax.swing.JPanel pnlProfileInfo;
    private javax.swing.JPanel pnlUserBankInformation;
    private javax.swing.JPanel pnlUserInformation;
    private javax.swing.JSpinner spnDay;
    private javax.swing.JTextField tbxDepositedCash;
    private javax.swing.JTextField tbxMax;
    private javax.swing.JTextField tbxMax1;
    private javax.swing.JTextField tbxMin;
    private javax.swing.JTextField tbxMin1;
    private javax.swing.JTextField tbxUserAge;
    private javax.swing.JTextField tbxUserEmail;
    private javax.swing.JTextField tbxUserFullName;
    private javax.swing.JTextField tbxUserGender;
    private javax.swing.JTextField tbxUserName;
    // End of variables declaration//GEN-END:variables

    private void switchPanel(JPanel panel) {
        pnlLayered.removeAll();
        pnlLayered.add(panel);
        pnlLayered.repaint();
        pnlLayered.validate();
    }
}
