/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Lian La-Fey
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderBtnGroup = new javax.swing.ButtonGroup();
        profPic_jFileChsr = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        fullName_JLabel = new javax.swing.JLabel();
        fullName_JText = new javax.swing.JTextField();
        password_JLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        pass_JPass = new javax.swing.JPasswordField();
        gender_JLabel = new javax.swing.JLabel();
        female_JRadio = new javax.swing.JRadioButton();
        male_JRadio = new javax.swing.JRadioButton();
        gender_JLabel1 = new javax.swing.JLabel();
        age_JText = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        profileAvatar_JLabel = new javax.swing.JLabel();
        profileAvatar_JLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        registerPanelPic = new javax.swing.JLabel();
        closeLogin_JLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(37, 41, 88));

        fullName_JLabel.setBackground(new java.awt.Color(255, 255, 255));
        fullName_JLabel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        fullName_JLabel.setForeground(new java.awt.Color(250, 233, 60));
        fullName_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fullName_JLabel.setText("Full Name");
        fullName_JLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        fullName_JText.setBackground(new java.awt.Color(37, 41, 88));
        fullName_JText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fullName_JText.setForeground(new java.awt.Color(255, 255, 255));
        fullName_JText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fullName_JText.setText("Lian La-Fey");
        fullName_JText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        fullName_JText.setOpaque(true);

        password_JLabel.setBackground(new java.awt.Color(255, 255, 255));
        password_JLabel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        password_JLabel.setForeground(new java.awt.Color(250, 233, 60));
        password_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        password_JLabel.setText("Password");
        password_JLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jSeparator1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 7, 1, 7));

        pass_JPass.setBackground(new java.awt.Color(50, 45, 44));
        pass_JPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pass_JPass.setForeground(new java.awt.Color(255, 255, 255));
        pass_JPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass_JPass.setText("adskasdkas");
        pass_JPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7));
        pass_JPass.setOpaque(true);

        gender_JLabel.setBackground(new java.awt.Color(255, 255, 255));
        gender_JLabel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        gender_JLabel.setForeground(new java.awt.Color(250, 233, 60));
        gender_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gender_JLabel.setText("Gender");
        gender_JLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        genderBtnGroup.add(female_JRadio);
        female_JRadio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        female_JRadio.setForeground(new java.awt.Color(255, 255, 255));
        female_JRadio.setSelected(true);
        female_JRadio.setText("Female");

        genderBtnGroup.add(male_JRadio);
        male_JRadio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        male_JRadio.setForeground(new java.awt.Color(255, 255, 255));
        male_JRadio.setText("Male");

        gender_JLabel1.setBackground(new java.awt.Color(255, 255, 255));
        gender_JLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        gender_JLabel1.setForeground(new java.awt.Color(250, 233, 60));
        gender_JLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gender_JLabel1.setText("Age");
        gender_JLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        age_JText.setBackground(new java.awt.Color(37, 41, 88));
        age_JText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        age_JText.setForeground(new java.awt.Color(255, 255, 255));
        age_JText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        age_JText.setText("21");
        age_JText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        age_JText.setOpaque(true);
        age_JText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                age_JTextKeyReleased(evt);
            }
        });

        jSeparator3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 7, 1, 7));

        jSeparator4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 7, 1, 7));

        profileAvatar_JLabel.setBackground(new java.awt.Color(255, 255, 255));
        profileAvatar_JLabel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        profileAvatar_JLabel.setForeground(new java.awt.Color(250, 233, 60));
        profileAvatar_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileAvatar_JLabel.setText("Select Profile Avatar");
        profileAvatar_JLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        profileAvatar_JLabel1.setBackground(new java.awt.Color(255, 255, 255));
        profileAvatar_JLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        profileAvatar_JLabel1.setForeground(new java.awt.Color(255, 255, 255));
        profileAvatar_JLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileAvatar_JLabel1.setText("Choose");
        profileAvatar_JLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 233, 60)));
        profileAvatar_JLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileAvatar_JLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator2)
                        .addComponent(password_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pass_JPass, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(age_JText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profileAvatar_JLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fullName_JText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(fullName_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gender_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gender_JLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(female_JRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(male_JRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(profileAvatar_JLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(fullName_JLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fullName_JText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gender_JLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(female_JRadio)
                    .addComponent(male_JRadio))
                .addGap(12, 12, 12)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(gender_JLabel1)
                .addGap(0, 0, 0)
                .addComponent(age_JText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profileAvatar_JLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profileAvatar_JLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(password_JLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pass_JPass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(250, 233, 60));

        registerPanelPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register.png"))); // NOI18N

        closeLogin_JLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        closeLogin_JLabel.setForeground(new java.awt.Color(37, 41, 88));
        closeLogin_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLogin_JLabel.setText("X");
        closeLogin_JLabel.setToolTipText("");
        closeLogin_JLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        closeLogin_JLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLogin_JLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerPanelPic)
                .addGap(63, 63, 63)
                .addComponent(closeLogin_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registerPanelPic, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(closeLogin_JLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeLogin_JLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLogin_JLabelMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_closeLogin_JLabelMouseClicked

    private void age_JTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_age_JTextKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_age_JTextKeyReleased

    private void profileAvatar_JLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileAvatar_JLabel1MouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog( null );
        File f = chooser.getSelectedFile();
    }//GEN-LAST:event_profileAvatar_JLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age_JText;
    private javax.swing.JLabel closeLogin_JLabel;
    private javax.swing.JRadioButton female_JRadio;
    private javax.swing.JLabel fullName_JLabel;
    private javax.swing.JTextField fullName_JText;
    private javax.swing.ButtonGroup genderBtnGroup;
    private javax.swing.JLabel gender_JLabel;
    private javax.swing.JLabel gender_JLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JRadioButton male_JRadio;
    private javax.swing.JPasswordField pass_JPass;
    private javax.swing.JLabel password_JLabel;
    private javax.swing.JFileChooser profPic_jFileChsr;
    private javax.swing.JLabel profileAvatar_JLabel;
    private javax.swing.JLabel profileAvatar_JLabel1;
    private javax.swing.JLabel registerPanelPic;
    // End of variables declaration//GEN-END:variables
}
